import { graphql } from "@/gql";

/**
 * GraphQL documents. `graphql()` is generated by GraphQL Codegen (client
 * preset) from schema.graphql, so every document below is type-checked
 * against the Strawberry schema and yields typed results.
 */

export const ActivityFields = graphql(/* GraphQL */ `
  fragment ActivityFields on Activity {
    id
    date
    startTime
    dayOfYear
    distanceKm
    durationSec
    paceSecPerKm
    calories
    avgCadence
    avgTempC
    elevationMinM
    elevationMaxM
    ascentM
    hasGps
    numPoints
    weather {
      description
      tempC
      humidityPct
      windKmh
    }
    warnings
  }
`);

export const MetaQuery = graphql(/* GraphQL */ `
  query Meta {
    meta {
      year
      generatedAt
    }
  }
`);

export const YearQuery = graphql(/* GraphQL */ `
  query Year {
    year {
      year
      totals {
        runs
        days
        activeDays
        distanceKm
        durationSec
        calories
        avgPaceSecPerKm
        avgCadence
        avgDistanceKm
      }
      monthly {
        month
        runs
        distanceKm
        durationSec
        calories
        avgPaceSecPerKm
        avgCadence
        bestPaceSecPerKm
        bestPaceActivityId
      }
      weekly {
        week
        weekStart
        runs
        distanceKm
        durationSec
        avgPaceSecPerKm
        longestKm
        activityIds
      }
      dailyDistance {
        date
        distanceKm
        activityId
      }
      trainingLoad {
        date
        ctl
        atl
        tsb
      }
      personalBests {
        longest {
          ...ActivityFields
        }
        fastest {
          ...ActivityFields
        }
        longestTime {
          ...ActivityFields
        }
        mostCalories {
          ...ActivityFields
        }
        topCadence {
          ...ActivityFields
        }
      }
    }
  }
`);

export const ActivitiesQuery = graphql(/* GraphQL */ `
  query Activities($fromDate: Date, $toDate: Date, $minKm: Float, $hasGps: Boolean) {
    activities(fromDate: $fromDate, toDate: $toDate, minKm: $minKm, hasGps: $hasGps) {
      ...ActivityFields
    }
  }
`);

export const ActivityQuery = graphql(/* GraphQL */ `
  query Activity($id: ID!) {
    activity(id: $id) {
      ...ActivityFields
    }
  }
`);

export const TrackQuery = graphql(/* GraphQL */ `
  query Track($id: ID!, $points: Int!) {
    activity(id: $id) {
      id
      track(points: $points) {
        sec
        lat
        lon
        elevationM
        distanceM
        speedMps
        cadence
        tempC
      }
    }
  }
`);

export const WeightQuery = graphql(/* GraphQL */ `
  query Weight($fromDate: Date, $toDate: Date) {
    weight(fromDate: $fromDate, toDate: $toDate) {
      date
      weightLbs
      weightKg
      bmi
    }
  }
`);

export const WeatherQuery = graphql(/* GraphQL */ `
  query Weather($fromDate: Date, $toDate: Date) {
    weather(fromDate: $fromDate, toDate: $toDate) {
      date
      maxTempC
      avgTempC
      minTempC
      humidityPct
      rainfallMm
      windKmh
      sunrise
      sunset
    }
  }
`);

export const WarningsQuery = graphql(/* GraphQL */ `
  query Warnings($fromDate: Date, $toDate: Date) {
    warnings(fromDate: $fromDate, toDate: $toDate) {
      date
      type
      signal
      startTime
      endTime
    }
  }
`);
